import type { Metadata } from 'next';
import Link from 'next/link';
import { Footer } from '../components/Footer';
import { SiteHeader } from '../components/SiteHeader';

export const metadata: Metadata = { title: 'About', description: 'About Vivek Rai, a visual designer with 5+ years of experience in corporate communication and digital design.' };

export default function AboutPage() {
  return <main id="top"><SiteHeader /><section className="about-statement section-pad"><figure className="about-statement__portrait"><img src="/about/bivek-rai.jpeg" alt="Bivek Rai" width={880} height={1280} loading="lazy" decoding="async" /><img className="about-statement__signature" src="/about/signature.png" alt="Bivek Rai signature" width={1920} height={1080} loading="lazy" decoding="async" /></figure><div><h1>About me</h1><p>I’m a Visual Designer with 5+ years of experience, specialising in corporate communication and digital design. My work includes annual reports, sustainability reports, quarterly reports, impact reports, high-end presentations, infographics, branding and marketing collaterals.</p><p>I’ve worked on projects for leading organisations across finance, manufacturing, insurance, healthcare and other industries, transforming complex information into clear, engaging and visually strong communication.</p><p>Alongside graphic design, I’m expanding into UI/UX and web design, using tools such as Figma and AI-powered development platforms to create modern digital experiences.</p><p>I enjoy combining design, storytelling, information hierarchy and technology to create work that is not only visually appealing, but also purposeful and easy to understand.</p></div></section><section className="expertise section-pad"><div className="section-label"><span>Expertise</span><span>Six connected disciplines</span></div>{['Annual & sustainability reports','Quarterly & impact reports','Presentation design','Infographics','Brand & marketing communication','UI/UX & web design'].map((item, index) => <div key={item}><span>0{index + 1}</span><h2>{item}</h2></div>)}</section><section className="about-tools section-pad"><h2>Tools</h2><p>Adobe InDesign · Illustrator · Photoshop · PowerPoint · Figma · After Effects</p><p>HTML · CSS · JavaScript · Next.js · AI-assisted workflows</p></section><section className="inline-cta section-pad"><p>Have a communication challenge?</p><Link href="/contact">Let&apos;s talk →</Link></section><Footer /></main>;
}
